# Site settings
title: Andrés Millán Alcaide
twitter_username: a_milln
name: Andrés Millán Alcaide

# Build settings
#markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: BitBucket
   url: https://bitbucket.org/%7Bf737f4d0-3071-49e2-981c-cf6740428edb%7D/
 - title: LinkedIn
   url: https://linkedin.com/in/andrés-millán-alcaide-914468145

#Any buzzword skills you want to include
skills:
- IoT
- Network simulations
- Alexa
- C++
- Human-Robot Interaction
- Chatbots
- Network Protocols
- Embedded Systems Programming

#Work experience is required
roles:
 - title: Personal Técnico de Apoyo (Technical Support Staff)
   start: 2019
   end:  2020
   employer: Research Management Service. Universidad de Córdoba
   description: In this work, integration systems were developed to facilitate administrative procedures for university researchers.
 - title: Research Internship
   start:  2017
   end: 2018
   employer: Computer & Electronics Engineering Department. Universidad de Córdoba
   description: During this stay, work and research has been done on the efficiency of various Network Communications in distributed and IoT environments. An efficient, closed-loop, communications protocol has been developed for a collaborative project with other universities.


#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2018
   subject: Computer Science (Computer Engineering mention)
   school: Universidad de Córdoba
   
 - level: Master of Science (M.Sc.)
   date: 2019
   subject: Electronics Systems for Smart Environments
   school: Universidad de Málaga


intro: |
  My name is Andrés Millán Alcaide, I am 23 years old and I have currently finished my Master's studies. Since I was a child, I have always been passionate about the world of technology, especially computers. I would like to focus my career on research and discover new models of interaction with the environment both at industrial and user level.<br/><br/>

  I have had experience working in research groups, hand in hand with great researchers.<br/><br/>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
   
